# Generated by Django 3.2.16 on 2022-12-27 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('price', models.BigIntegerField(default=0)),
                ('category', models.CharField(max_length=200)),
            ],
        ),
    ]
