# Generated by Django 4.1.4 on 2022-12-29 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("desc", models.CharField(max_length=400)),
                ("price", models.FloatField(default=0)),
                ("disc_price", models.FloatField(default=0)),
                ("img", models.CharField(max_length=200)),
                ("category", models.CharField(max_length=200)),
            ],
            options={"db_table": "item",},
        ),
    ]
